### ISSUE TITLE
PyCIM16

### ISSUE THREAD

**Issue by hajef** [rwl/PyCIM#24]
Dear all,
I'd like to bring PyCIM to the next step that means implementing the CIM 16 standard and need every help I can get. I am new to GitHub and PyCIM as well so I prefer to just contribute to this project instead of fork it and make my own PyCIM 16 repository.

**Comment by stv0g** [comment]
Hi @hajef,

I have a similar motivation. We should try to document and automate the code generation flow of PyCIM. To do so, I created a new issue #26.

**Comment by hajef** [comment]
That should do tha trick. :D
