### ISSUE TITLE
IEC62325-351 compatibility

### ISSUE THREAD

**Issue by JrtPec** [rwl/PyCIM#25]
Hi,

I'm building [a Python client for the ENTSO-E API](https://github.com/EnergieID/entsoe-py) (European network of transmission system operators for electricity).

All API responses are formatted along IEC62325-351. (see https://www.entsoe.eu/major-projects/common-information-model-cim/cim-for-energy-markets/Pages/default.aspx, https://www.entsoe.eu/major-projects/common-information-model-cim/Pages/default.aspx)

[Attached is a sample response I got](https://github.com/rwl/PyCIM/files/1144777/entsoe_sample.txt). I tried running it through PyCIM, but it doesn't create any objects.
What would it take to get this working? How can I assist?

**Comment by rwl** [comment]
PyCIM supports parsing and serialisation of CIM RDF/XML files according to IEC 61970-552.

You could just to parse the XML into a DOM tree and query for the data that you need:

https://gist.github.com/rwl/396e35aa41919714b0a1
